# permissions for end users to edit releasers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: releaser-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: release-tool
    app.kubernetes.io/part-of: release-tool
    app.kubernetes.io/managed-by: kustomize
  name: releaser-editor-role
rules:
- apiGroups:
  - devops.release.io
  resources:
  - releasers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.release.io
  resources:
  - releasers/status
  verbs:
  - get
