---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - devops.release.io
  resources:
  - imagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.release.io
  resources:
  - imagers/finalizers
  verbs:
  - update
- apiGroups:
  - devops.release.io
  resources:
  - imagers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - devops.release.io
  resources:
  - releasers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.release.io
  resources:
  - releasers/finalizers
  verbs:
  - update
- apiGroups:
  - devops.release.io
  resources:
  - releasers/status
  verbs:
  - get
  - patch
  - update
